sudo: required
dist: bionic
language: minimal
services:
  - docker

env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: "unzeKg7LmtpDZvEqH7Wtp602cSVcYMf/Xf86h9buIX0vML1Ylu1YvupJBVhZqX9bZC3HgJR3LTXjwukwJvhHhD3beffOJvcdObg7ogYs+HAalWjwjZ3gxXOpKmw4Pxnnkx4I4h8UqOrCocV6lG3ASsj/8o6sxSH+c4zwrkAAGn79ZNlXfRjXiV3Sgnhz93jWYVZu/c2eW4S7ShksGcyXZsJb6oNdQc44sd1Cy/95ZNtG6FGX4mQDrvT47ZYvy4EdgM1aDl6hwWB3Au6g9tBDXSEMjQzekMmGVh4jVsih9D5ee+i41+h/fnI9RKp1XFYP80Mcbi6uZkW4SFl5anuKEyn3MH7HmKmcpkrJshucKWZRdmCTkG887KsgRUAXSu6mtlGk7cXkLH/a5tWtPfJF1FVIjRifEPqctO26Oz3lgAOKpjGOS1FbU0H7DrAV0m3WusjHC1UBfOjWvcJiCDi94UdSD24UZ/UVdiNoHz7GJLId6P0ZFXUpua6NByLlFDPaKZwePDcjunJckCdQiqZ2M4HAAChCJyMh7ZZAu+3n9ix7FVmv9++A7zFGQyDe0l1sDRq/1Vere7ywuvY3UA51WeMRlgJ4zP8GeajZfd7ykvc/QReFmgcxJg46YMF5NuizYD2rfLISjuT3LO0ULsWp+PNBpgyu1J65AcYFBi6nDk0="
    # AWS_SECRET_ACCESS_KEY
    - secure: "HvJtY+C4qXCAmzFI8NVIc8ZwW6yLhWvN8vTwlvRpDdAYJmwcKD0hh+SmFmBWuGwkSeneehYF5jpghMeKeyJi86Fls0EhCz7X8As5GjtCwP/q5+16uz5w0ojZwqGrYGh2DweYyWIO42+3rxaYrbcHu+j2vWf3iOvOYBKpps4MmQTqRuAIdcRe4P0jOBsvXJNjiXrAA2LHtSPQadJAxQja2W7h0qZ0/G2soVY6nAhABHkn23XWuKbDvwjH7CQzbcOdHXzQJKbqbLSjHU9fOGtkpSGQQ/KHHu+V8LEfy4CanauyKRllEo/MMKdsap7KOyOv/degP5xwr4m9TFOGqf5SvOyKLHxwkBimoUMrfrEDz8WllctIA/3suHrad/4GJcmeYHRCBK1GYunbD4v8lAZVuHZng/z+6d975BRZT8QukEhEdtkOxc5z3R55KtGclDOThYerYsJqmPgwZ1vlwpFO+Eflzo4F1a29P+xVlXRkuSABfToa9JP059RAcZGgJt8vz0XpsdC6k/pWdciiSI3Xk5T2VxjkHFL3FePWIATiP4ZvnMrP5GWfT+yCZdwPX7XAr/t2UVADgo6I4zDXEkjFNdmhJYxaD1U1m5BWNfWJ7+558UPWOSv6SbI3uoUjJxGy5IZVvCT201yrbOFs0DtDDoyfqKI/8MlhMBuyUzwbcOY="
    # GITHUB_TOKEN
    - secure: "MbGdAELFob+kL2xaFHREcuSerUA3MCo3txlJAUqCvRzLcDLRvpC4VCyrD1M/VD/j5ijYYVYj96NZ03Gm33M4m0U0OpCnlDunqcpX5ET6JkSZcsrEtCAIciEWBVrqEbKoC1p//CaolSRXo+5023VyUb9+ECeZzc8BV72/ADC/DYBEsaz0VBpajzeT0z9yxEZTbtC2+/b0dx327O/4RXF0cYqFbqfILpdiiAef1oFv8UToN7nD/albJm88IOyOFBXEZmmFX2xkmOGzmcwNzv2rYOKn+ba5BAtlO+vCKb2ty7vWFUAwHBpB+tsSe6rhD5yxGQECZrDBPbu4BX/lPRJXF8PAzsGQxZ9Rzxa81t1e9yLyXUEr/DAPduJPiowFis2oGtSKSwpoF8q94XC4axY+F1Sr8hK/FGkiGLQ+KXI96os+bZ20xVJrkAGbYqPhtPxuuYvYL+XR5fWZ3J3e5lxfallDOSoNQAYOLR3lG7zb3QWrWr1aEXZ7A3/HZWEWlx793ft6dUtJgki02Z8200Ty0fSDYLFZPtOypgWFtbkyJIHWJkSfKPtIcRtdozeLgxZCFXXC3Edv30KNsk839wjVGoxsChI4KtEQa1d94s5rlFcE5rA0w74x1C6r2sMdla/eJqWJm9GEuyPYVAFIWwv4B/gC/R0+LrWxcxU/YzDQnVY="
    # FLOW_TOKEN
    - secure: "WRMLVldj0/pe0tcDSz7I+3+av+i032nUb/hFGAubmfKngBIA/zToQY2DWms6hpFN6HEEecwzyMyz+RcU+2p+IXVjHtDZE703YwbBFd4gfdrGcnSlRmf8GqMeio59jdNFABIWbEImD42tLuKvY6jUjBcXFioVNxvy0ZMxPoK29BTxSf4qjLoh3QBDVto5vYrhRdpXcEAu8HAP9nRIrYznA4N1htRSEnuNRi25x4ZFlovbJZ6UERGy6AyYAPHMJayHucNRM+ignvvbATPy7OJhepmEFagqvlBebH7HOxtAT0HLkfGYJZdVZu2K4WSE/ecL2255HafgLUEnGGKrm+FZMwnV3MbcdIy+bKopgQV07ufB9yQJgW/iR7F7vzCfxCLV73n8HHeAw41YPln1ue8GdVrJDfu9OPKpag9vyaO3ASbrhwlRIptDYdPT3/CJlgTQkG+mz7qdZNfmCxhHUuT7xL4ugzBJAirekTfB6TrTH8e4REzuu8EbLf6uCXZ8UrTW3oTv76KRZP3DVF/Z+ue5QzsKhSW4WEOT64n2ItICGEFKeEn5a2IENGqGs2WVwWwlMWlnIeym2+SEDiMooRb2q3xz1g1OYA9/HL3iv8yaNoDGiBbqAYpa+xx8Lq0Xk1bzRNlDBCBwYPUSRLAe2jLqQMOuwSUPGTJWCLECQdlqRCU="

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export BUILD_TIME="$(date -u --iso-8601=seconds)"

script:
  - docker build --label BaseimageType="fatjar-openjdk8" --label BaseimageBuildNumber=ci-${TRAVIS_BUILD_NUMBER} --label BaseimageBuildTime=${BUILD_TIME} -t ${ECR_REPO}/baseimage-fatjar-openjdk8:ci-${TRAVIS_BUILD_NUMBER} --build-arg OPENJDK_VERSION=openjdk8 --build-arg SERVICE_KIND=fatjar --build-arg TOMCAT_VERSION=tomcat7 .
  - docker build --label BaseimageType="fatjar-openjdk11" --label BaseimageBuildNumber=ci-${TRAVIS_BUILD_NUMBER} --label BaseimageBuildTime=${BUILD_TIME} -t ${ECR_REPO}/baseimage-fatjar-openjdk11:ci-${TRAVIS_BUILD_NUMBER} --build-arg OPENJDK_VERSION=openjdk11 --build-arg SERVICE_KIND=fatjar --build-arg TOMCAT_VERSION=tomcat7 .
  - docker build -f Dockerfile-corretto --label BaseimageType="fatjar-openjdk17" --label BaseimageBuildNumber=ci-${TRAVIS_BUILD_NUMBER} --label BaseimageBuildTime=${BUILD_TIME} -t ${ECR_REPO}/baseimage-fatjar-openjdk17:ci-${TRAVIS_BUILD_NUMBER} --build-arg OPENJDK_VERSION=17 --build-arg SERVICE_KIND=fatjar --build-arg TOMCAT_VERSION=tomcat7 .
  - docker build --label BaseimageType="war-openjdk8" --label BaseimageBuildNumber=ci-${TRAVIS_BUILD_NUMBER} --label BaseimageBuildTime=${BUILD_TIME} -t ${ECR_REPO}/baseimage-war-openjdk8:ci-${TRAVIS_BUILD_NUMBER} --build-arg OPENJDK_VERSION=openjdk8 --build-arg SERVICE_KIND=war --build-arg TOMCAT_VERSION=tomcat7 .
  - docker build --label BaseimageType="war-tomcat8-openjdk8" --label BaseimageBuildNumber=ci-${TRAVIS_BUILD_NUMBER} --label BaseimageBuildTime=${BUILD_TIME} -t ${ECR_REPO}/baseimage-war-tomcat8-openjdk8:ci-${TRAVIS_BUILD_NUMBER} --build-arg OPENJDK_VERSION=openjdk8 --build-arg SERVICE_KIND=war-tomcat8 --build-arg TOMCAT_VERSION=tomcat8 .
  - docker build --label BaseimageType="war-openjdk11" --label BaseimageBuildNumber=ci-${TRAVIS_BUILD_NUMBER} --label BaseimageBuildTime=${BUILD_TIME} -t ${ECR_REPO}/baseimage-war-openjdk11:ci-${TRAVIS_BUILD_NUMBER} --build-arg OPENJDK_VERSION=openjdk11 --build-arg SERVICE_KIND=war --build-arg TOMCAT_VERSION=tomcat7 .
  - docker build --label BaseimageType="war-tomcat8-openjdk11" --label BaseimageBuildNumber=ci-${TRAVIS_BUILD_NUMBER} --label BaseimageBuildTime=${BUILD_TIME} -t ${ECR_REPO}/baseimage-war-tomcat8-openjdk11:ci-${TRAVIS_BUILD_NUMBER} --build-arg OPENJDK_VERSION=openjdk11 --build-arg SERVICE_KIND=war-tomcat8 --build-arg TOMCAT_VERSION=tomcat8 .
  - bash version_check/version_check.sh
  - docker images

deploy:
  - provider: script
    script: ./ci-tools/build/upload-image.sh baseimage-fatjar-openjdk8 $TRAVIS_BRANCH
    on:
      all_branches: true
  - provider: script
    script: ./ci-tools/build/upload-image.sh baseimage-fatjar-openjdk11 $TRAVIS_BRANCH
    on:
      all_branches: true
  - provider: script
    script: ./ci-tools/build/upload-image.sh baseimage-fatjar-openjdk17 $TRAVIS_BRANCH
    on:
      all_branches: true
  - provider: script
    script: ./ci-tools/build/upload-image.sh baseimage-war-openjdk8 $TRAVIS_BRANCH
    on:
      all_branches: true
  - provider: script
    script: ./ci-tools/build/upload-image.sh baseimage-war-tomcat8-openjdk8 $TRAVIS_BRANCH
    on:
      all_branches: true
  - provider: script
    script: ./ci-tools/build/upload-image.sh baseimage-war-openjdk11 $TRAVIS_BRANCH
    on:
      all_branches: true
  - provider: script
    script: ./ci-tools/build/upload-image.sh baseimage-war-tomcat8-openjdk11 $TRAVIS_BRANCH
    on:
      all_branches: true
