name: Baseimage

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * 1'
    - cron: '*/30 * * * *'
  push:
    paths-ignore:
      - '**.md'

env:
  ECR_REPO: 190073735177.dkr.ecr.eu-west-1.amazonaws.com/utility

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: write    # This is required for actions/checkout read/write

jobs:

  update-packages:
    if: ${{ github.event_name == 'schedule' }}
    runs-on: ubuntu-latest
    concurrency: 1
    strategy:
      matrix:
        jdk: [8, 11, 17, 21]
        servicekind: [fatjar, war]
        tomcat: [tomcat9, tomcat10]
        exclude:
          - jdk: 17
            servicekind: war
          - servicekind: fatjar
            tomcat: tomcat10
          - jdk: 8
            tomcat: tomcat10

    env:
      PILVIKEHITYS_SLACK_TOKEN: ${{ secrets.PILVIKEHITYS_SLACK_TOKEN }}
      LOCAL_TAG: localhost:5001/actions/
    services:
      registry:
        image: registry:2
        ports:
          - 5001:5000
    steps:
      - name: Set up variables
        shell: bash
        run: |
          echo "IMAGE_LABEL=ga-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date --iso-8601=seconds)" >> $GITHUB_ENV
          if (${{ matrix.servicekind == 'war' }} && ${{ matrix.tomcat == 'tomcat9' || matrix.tomcat == 'tomcat10' }});
          then
            echo "FOLDER=${{ matrix.servicekind }}-${{ matrix.tomcat }}-openjdk${{ matrix.jdk }}" >> $GITHUB_ENV
          else
            echo "FOLDER=${{ matrix.servicekind }}-openjdk${{ matrix.jdk }}" >> $GITHUB_ENV
          fi
          if [ "${{ matrix.jdk }}" = "8" ]
          then
            echo "DOCKERFILE=Dockerfile-8" >> $GITHUB_ENV
          else
            echo "DOCKERFILE=Dockerfile" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v4
      - name: Build image and check packages
        shell: bash
        run: |
          docker build --build-arg SERVICE_KIND=${{ matrix.servicekind }} --build-arg OPENJDK_VERSION=${{ matrix.jdk }} --build-arg TOMCAT_VERSION=${{ matrix.tomcat }} --build-arg FOLDER=$FOLDER -f $DOCKERFILE -t test-alpine .
          docker run -u root -v $(pwd)/variants/$FOLDER:/repository test-alpine /bin/sh -c "apk info -v | sort > /repository/package-versions && chmod 755 /repository/package-versions"
          
          if ! [[ -z $(git --no-pager diff --numstat $(pwd)/variants/$FOLDER/package-versions) ]]; then
            echo "Updating packages"
            git config --global user.name "Github Actions"
            git config --global user.email "github-actions@opintopolku.fi"
            git commit -a -m 'Update baseimage packages' || true
            git push origin "HEAD:${GITHUB_REF_NAME}"
            curl -H "Content-Type: application/json" -X POST \
              --data "{\"text\": \"Baseimage: packages updated by Github Actions\"}" \
              ${PILVIKEHITYS_SLACK_TOKEN} 
          else
            echo "No update needed"
          fi
    
  build:
    if: ${{ github.event_name != 'schedule' }}
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: true
      matrix:
        jdk: [8, 11, 17, 21]
        servicekind: [fatjar, war]
        tomcat: [tomcat9, tomcat10]
        exclude:
          - servicekind: fatjar
            tomcat: tomcat10
          - jdk: 17
            servicekind: war
          - jdk: 8
            tomcat: tomcat10

    steps:
      - uses: actions/checkout@v4

      - name: Set up variables
        shell: bash
        run: |
          echo "IMAGE_LABEL=ga-${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "BUILD_TIME=$(date --iso-8601=seconds)" >> $GITHUB_ENV
          if (${{ matrix.servicekind == 'war' }} && ${{ matrix.tomcat == 'tomcat9' || matrix.tomcat == 'tomcat10' }});
          then
            echo "FOLDER=${{ matrix.servicekind }}-${{ matrix.tomcat }}-openjdk${{ matrix.jdk }}" >> $GITHUB_ENV
          else
            echo "FOLDER=${{ matrix.servicekind }}-openjdk${{ matrix.jdk }}" >> $GITHUB_ENV
          fi
          if [ "${{ matrix.jdk }}" = "8" ]
          then
            echo "DOCKERFILE=Dockerfile-8" >> $GITHUB_ENV
          else
            echo "DOCKERFILE=Dockerfile" >> $GITHUB_ENV
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OPH_UTILITY_ROLE_ARN }}
          role-session-name: baseimage-deploy-${{ env.FOLDER }}
          aws-region: eu-west-1

      - name: Get ECR Registry
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker meta for alpine images
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.ECR_REPO }}/baseimage-${{ env.FOLDER }}
          tags: |
            type=raw,value=${{ env.IMAGE_LABEL }}
            type=raw,value=${{ github.ref_name }}
          labels: |
            BaseimageType=${{ matrix.servicekind }}-openjdk${{ matrix.jdk }}
            BaseimageBuildNumber=${{ env.IMAGE_LABEL }}
            BaseimageBuildTime=${{ env.BUILD_TIME }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
      
      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.ecr-login.outputs.registry }}

      - name: Build and export to Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.DOCKERFILE }}
          push: true
          platforms: linux/amd64, linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SERVICE_KIND=${{ matrix.servicekind }}
            OPENJDK_VERSION=${{ matrix.jdk }}
            TOMCAT_VERSION=${{ matrix.tomcat }}
            FOLDER=${{ env.FOLDER }}
      
      - name: Update build metadata
        shell: bash
        run: |
          aws dynamodb put-item --table-name builds --item "{\"Service\": {\"S\": \"$FOLDER\"}, \"Build\": {\"S\": \"$IMAGE_LABEL\"}, \"Branch\": {\"S\": \"$GITHUB_REF_NAME\"}, \"Commit\": {\"S\": \"$GITHUB_SHA\"}, \"Time\": {\"S\": \"$BUILD_TIME\"}}" --condition-expression "attribute_not_exists(Id)" --region eu-west-1

